apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-worker
  labels:
    app: parent-worker
spec:
  selector:
    matchLabels:
      app: parent-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: parent-worker
    spec:
      dnsPolicy: Default
      volumes:
        - name: google-secret
          secret:
            secretName: google-secret
        - name: chunkedgraph-secret
          secret:
            secretName: chunkedgraph-secret             
        - name: microns-seunglab-google-secret
          secret:
            secretName: microns-seunglab-google-secret
        - name: seunglab2-google-secret
          secret:
            secretName: seunglab2-google-secret
        # - name: ranl-scratch-google-secret
          # secret:
            # secretName: ranl-scratch-google-secret
      containers:
        - name: parent-worker
          image: gcr.io/neuromancer-seung-import/pychunkedgraph:manuel-mesh
          imagePullPolicy: Always
          resources:
            requests:
              memory: 600G
          env:
            - name: APP_SETTINGS
              value: pychunkedgraph.app.config.DeploymentWithRedisConfig
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/google-secret.json              
            - name: FLASK_APP
              value: run_dev.py
            - name: REDIS_PASSWORD
              value: dev # for development
          volumeMounts:
            - name: google-secret
              mountPath: /root/.cloudvolume/secrets/google-secret.json
              subPath: google-secret.json
              readOnly: true
            - name: chunkedgraph-secret
              mountPath: /root/.cloudvolume/secrets/chunkedgraph-secret.json
              subPath: chunkedgraph-secret.json
              readOnly: true                  
            - name: microns-seunglab-google-secret
              mountPath: /root/.cloudvolume/secrets/microns-seunglab-google-secret.json
              subPath: microns-seunglab-google-secret.json
              readOnly: true                
            - name: seunglab2-google-secret
              mountPath: /root/.cloudvolume/secrets/seunglab2-google-secret.json
              subPath: seunglab2-google-secret.json
            #   readOnly: true
            # - name: ranl-scratch-google-secret
            #   mountPath: /root/.cloudvolume/secrets/ranl-scratch-google-secret.json
            #   subPath: ranl-scratch-google-secret.json
            #   readOnly: true              
          # command: ["rq"]
          # args: ["worker", "-c", "rq_workers.parent"]
          command: [bash, -c, "trap : TERM INT; sleep infinity & wait"]
      nodeSelector:
        cloud.google.com/gke-nodepool: parents-high